### ISSUE TITLE
Conjurer bugs

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#101]
Bug 1
I had this run into me when I was trying to find a conjurer theater.

I scanned for a theater and it could not find one in it's max radius of 2500 (I swear it was 10k blocks at one point). I ened up needing to find one so I turned on cheats and used /locate it ened up being 3500 blocks away on the x coordinate away from 0,0. If I did not use locate I could have not been able to find it.

Bug 2
Sometimes the conjurer will not drop his hat so there is a chance it does not complete the quest. 
_This could be a random glitch tho since I only had this happen once._

**Comment by uthw** [comment]
Bug 1 is caused by the max sample size being lower than the max radius when the Explorer's Compass searches for a Theatre, causing it to report "not found" prematurely. I increased the sample size in the config so this should no longer happen.

The conjurer's quest checks for when you kill a conjurer, not when you obtain a Conjurer Hat. what happened was you somehow didn't get credit for killing the Conjurer so the quest didn't complete. Maybe he fell in lava or was killed by another mob. Or, you didn't kill the Wroughtnaut which wouldn't trigger the quest because completing the Conjurer quest requires completing the Wroughtnaut quest first.

**Comment by Guineapigboyx** [comment]
My best guess is that I had frost aspect on my sword and that killed him, what for some reason did not count as me killing him.
