### ISSUE TITLE
Grapaling hook does not function

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#102]
A video of me trying to use it and it not working.
https://github.com/user-attachments/assets/5d4ab9b0-4301-4284-886a-d6aa79a3333a

I did also try it with controller input, keyboard key, and mouse click and none seam to work. I also did try rebooting my game and that did not fix it.

_It could be it is because it is a normal graphing hook opposed to a modified maybe._

**Comment by uthw** [comment]
This is caused by grappling hook mod being incompatible with newer versions of Forge. You can fix this by replacing Forge with NeoForge. Any version is fine but I'd go with the latest shown in Prism. You'll also need to replace Better Combat 1.8.6 with 1.8.5, **pasted in from an instance of Mincemeat 2 v0.4.1 - 0.4.6**, it won't work if you download it online.
