### ISSUE TITLE
Blue skies issues

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#115]
To little documentation/quests on blue skies.

They do not explain much of anything with the only thing being that there are 2 dungeons and you should find them And that the name of the 1st dungeon and the gate keeper house exists. 
At Least put the name of the the 2nd dungeons Since it can be hard to find since they spawn very infrequently, and the poison dungeon is near impossible to find without a compass or looking it up on the wiki since it is just a big tree what can be hard to find even when the compass is telling you where it is. 
Also put in the minerals like Diopside and Charoite since if you don't know they are there is a chance you will not find them. (like i never even found Charoite when i was mining). You could even put the special ones in there like Ventium,Falsite,Horizonite

_heck you could even copy and paste the ones from mince mince one since they were really good_

Like compare mincemeat 2 with mincemeat 1 and you can see the staggering difference.

Mincemeat 2
![image](https://github.com/user-attachments/assets/8cb633af-b460-4c1e-9c34-5dbaa9abdca5)

Mincemeat 1
![image](https://github.com/user-attachments/assets/defb41cc-959e-4bab-8b60-8ddca9306827)

heck even the progression tab in mincemeat 1 has technically has more information since it says the name of 2nd dungeon you need to find.
![image](https://github.com/user-attachments/assets/f4a309b3-926e-42ce-8e60-7d05b9515e85)

------------------------------------------------------------------

Make Blue skies pickaxes have better combat.
- In the ever bright you need to use a pickax as a weapon to kill multiple mobs effectively.

------------------------------------------------------------------

Make stardust rams drop more wool.
- If you it could be nice since it would give a way to get insulation in the ever bright 
- You could also do something similar for cosmic foxes and fox pelts

------------------------------------------------------------------

Make moonstone spears stronger/have more range
- They only do 4 damage what is kinda of pitiful
- They have equal range to a sword also so they don't have much of a purpose there either

**Comment by uthw** [comment]
Completed:
Blue Skies now has some quests covering a few items and mechanics specific to the dimensions, including metals and gems
Every quest now has the name of the dungeon you're required to visit

Not planned:
Stardust rams can be sheared for wool, and I don't want to incentivize killing them because it's not sustainable. If you're curious, this is mentioned in the bestiary.
Moonstone spears dislike having their damage edited. Also, they have the same range as spears from Spartan Weaponry, but their sprite is deceptively small so you'd think they're the same

Also, it would help if you opened a new issue for each of these next time, you don't have to but it's easier for me to keep track of.
