### ISSUE TITLE
The Spwaters in the Starlight crsher fight can spawn as super strong bosses

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#118]
They should not be able to spawn as bosses, this also goes for the snow owls. This also most likely applies to Artificial golems.

![image](https://github.com/user-attachments/assets/bcfbe1c3-03f9-4e98-8ffc-f9bfb53bae4f)
It has 100 HP and has an instant /poison field

**Comment by uthw** [comment]
Yeah, since the Champions config was ported directly from Mincemeat 1, any mobs added by mods in 2 will be able to spawn as champions. In the next version, I'll add bosses and mobs related to them to the blacklist like how it was in Mincemeat 1. 

Though, in this case I don't think we really tested the Starlit Crusher fight in Mincemeat 1 so the Spewter ended up flying under the radar.
