### ISSUE TITLE
Botainia is not linked to natures aura even tho you need to do it.

### ISSUE THREAD

**Issue by Guineapigboyx** [uthw/Mincemeat-2#135]
### Affected quests

Anceint sapaling

### Does it prevent you from progressing through the quests?

NO

### If this is a bug, does it only happen in the latest version?

None

### If this is not a bug, is it a suggestion/feature request?

None

### Describe the issue

Currently, if you were to nature aura before botaina you would be confused why it feels like you skipped an entire part of magic when you get to ancient sapling since you need to get mana infusion to make the runes to make the sapling.

### Add additional context

Also technically you need to get to ars nova before even starting Nature's aura also.

**Comment by uthw** [comment]
It wasn't until later into Mincemeat 1 that Botania was dependent on Nature's Aura (iirc Botania was added first) so the quests were designed as if you can do whichever one you want. Since this seems confusing now, I'll fix the chapter to make it obvious you need Nature's Aura to do Botania.

I'll also make Enchanting Apparatus a prerequisite for Nature's Aura so the entire natural magic chapter will be hidden until you're actually able to start it.
